version: 0.0
os: linux
files:
  - source: /
    destination: /home/rentling/webroot-new/

hooks:
   BeforeInstall: 
     - location: /before-install.sh
       timeout: 180
       runas: root
   AfterInstall:
     - location: /deploy.sh
       timeout: 6000
       runas: root