<?php

return [
    'status' =>[
        'RELAY_STATUS_SUBMITTED' => 0,
        'RELAY_STATUS_CAPTURED_FROM_TENANT' =>1,
        'RELAY_STATUS_SUBMITTED_FOR_RELEASE_TO_LANDLORD' =>2,
        'RELAY_STATUS_RELEASED_TO_LANDLORD' => 3,
        'RELAY_STATUS_CANCEL_BY_TENANT' => 4,
        'RELAY_STATUS_CANCEL_BY_LANDLORD' =>5
    ]

];